name: Swift

on:
  pull_request:
    branches: [ '**' ]

jobs:
  build_macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v

#   build_ubuntu:
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2
#     - name: Build
#       run: swift build -v
#     - name: Run tests
#       run: swift test -v
